/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BeerRequest } from './models/beer-request';
export type { BeerResponse } from './models/beer-response';
export type { BeerTypeRequest } from './models/beer-type-request';
export type { BeerTypeResponse } from './models/beer-type-response';
export type { PaginatedResponseBeerResponse } from './models/paginated-response-beer-response';
export type { PaginatedResponseBeerTypeResponse } from './models/paginated-response-beer-type-response';
