/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BeerResponse } from '../../models/beer-response';

export interface GetBeer$Params {
  'beer-id': string;
}

export function getBeer(http: HttpClient, rootUrl: string, params: GetBeer$Params, context?: HttpContext): Observable<StrictHttpResponse<BeerResponse>> {
  const rb = new RequestBuilder(rootUrl, getBeer.PATH, 'get');
  if (params) {
    rb.path('beer-id', params['beer-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BeerResponse>;
    })
  );
}

getBeer.PATH = '/beers/{beer-id}';
