/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResponseBeerResponse } from '../../models/paginated-response-beer-response';

export interface GetBeerByBeerType$Params {
  'beer-type': string;
  page?: number;
}

export function getBeerByBeerType(http: HttpClient, rootUrl: string, params: GetBeerByBeerType$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedResponseBeerResponse>> {
  const rb = new RequestBuilder(rootUrl, getBeerByBeerType.PATH, 'get');
  if (params) {
    rb.path('beer-type', params['beer-type'], {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedResponseBeerResponse>;
    })
  );
}

getBeerByBeerType.PATH = '/beers/type/{beer-type}';
