/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BeerTypeRequest } from '../../models/beer-type-request';
import { BeerTypeResponse } from '../../models/beer-type-response';

export interface UpdateBeerType$Params {
  'beer-type-id': string;
      body: BeerTypeRequest
}

export function updateBeerType(http: HttpClient, rootUrl: string, params: UpdateBeerType$Params, context?: HttpContext): Observable<StrictHttpResponse<BeerTypeResponse>> {
  const rb = new RequestBuilder(rootUrl, updateBeerType.PATH, 'put');
  if (params) {
    rb.path('beer-type-id', params['beer-type-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BeerTypeResponse>;
    })
  );
}

updateBeerType.PATH = '/beer-types/{beer-type-id}';
