/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BeerTypeResponse } from './beer-type-response';
export interface BeerResponse {
  alcoholPercentage?: number;
  beerType?: BeerTypeResponse;
  createdAt?: string;
  description?: string;
  id?: string;
  modifiedAt?: string;
  name?: string;
  pictureUrl?: string;
  releasedAt?: string;
}
