/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BeerRequest {
  alcoholPercentage: number;
  beerTypeId: string;
  description: string;
  name: string;
  releasedAt: string;
}
