/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BeerTypeResponse {
  createdAt?: string;
  description?: string;
  id?: string;
  name?: string;
  updatedAt?: string;
}
