/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BeerTypeResponse } from './beer-type-response';
export interface PaginatedResponseBeerTypeResponse {
  content?: Array<BeerTypeResponse>;
  page?: number;
  pageSize?: number;
  totalItems?: number;
  totalPages?: number;
}
