/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BeerResponse } from './beer-response';
export interface PaginatedResponseBeerResponse {
  content?: Array<BeerResponse>;
  page?: number;
  pageSize?: number;
  totalItems?: number;
  totalPages?: number;
}
